version: "3.8"
services:
  mongodb: #this is the local db in docker
    image: mongo:5
    restart: always
    ports:
      - 27017:27017

  mongo-seed: #this is used to populate the DB, see dockerfile for import command
    image: cloudburstacr.azurecr.io/mongo-seed
    build:
      context: ./db-seed
    depends_on:
      - mongodb

  api:
    image: cloudburstacr.azurecr.io/api
    build:
      context: ./api
    environment:
      PORT: 4000
      MONGO_URI: mongodb://mongodb:27017/dobook
    depends_on:
      - mongodb

  frontend:
    image: cloudburstacr.azurecr.io/frontend
    build:
      context: ./frontend
    environment:
      API_HOST: api
      API_PORT: 4000
    links:
      - api
    ports:
      - 80:80
  
  real-world-example-app:
    image: cloudburstacr.azurecr.io/real-world-example-app
    build:
      context: ./real-world-example-app