version: "3"
services:
  mongo-seed: #this is used to populate the DB, see dockerfile for import command
    build:
      context: ./db-seed
    environment:
      # URI removed for security
    image: cloudburstacr.azurecr.io/mongo-seed
          
  api:
    build:
      context: ./api
    image: cloudburstacr.azurecr.io/api
    environment:
      PORT: 4000
      # URI removed for security

  frontend:
    build:
      context: ./frontend
    image: cloudburstacr.azurecr.io/frontend
    depends_on:
      - api
    environment:
      API_HOST: api
      API_PORT: 4000
    ports:
      - "80:80"
