version: "3"
services:
  mongodb: 
    image: cloudburstacr.azurecr.io/mongo

  mongo-seed: #this is used to populate the DB, see dockerfile for import command
    build:
      context: ./db-seed
      args:
        HOST: cloudburst-mongodb.mongo.cosmos.azure.com
        PORT: 10255
    image: cloudburstacr.azurecr.io/mongo-seed
    depends_on:
      - mongodb
          
  api:
    build:
      context: ./api
    image: cloudburstacr.azurecr.io/api
    depends_on:
      - mongodb
    environment:
      PORT: 4000
      # MONGO_URI: ${MONGO_URI}
      MONGO_URI: mongodb://cloudburst-mongodb.mongo.cosmos.azure.com:10255/dobook

  frontend:
    build:
      context: ./frontend
    image: cloudburstacr.azurecr.io/frontend
    depends_on:
      - api
    environment:
      API_HOST: api
      API_PORT: 4000
    ports:
      - "80:80"
