name: MongoDB Backup Schedule Job

on:
 # schedule:
 #   - cron: '*/5 * * * *' 
  push:
    branches:
      - challenge-14

jobs:
  mongodump:
    runs-on: ubuntu-latest
    steps:
      - uses: gabrielrufino/mongodump-action
        with:
          connection-string: ${{ secrets.MONGO_URI }}
      - uses: actions/upload-artifact@v3
        with:
          name: dump
          path: ${{ github.workspace }}/dump
     