name: MongoDB Backup Schedule Job

on:
 # schedule:
 #   - cron: '*/5 * * * *' 
  push:
    branches:
      - challenge-14

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: mongodump docker job
    steps:
      - name: mongodump command
        id: hello
        uses: .github/actions/mongodump.yml