# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code, and run tests across different versions of node
# For more information, see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        project: [frontend, api]

    defaults:
      run:
        working-directory: ./application/${{ matrix.project }} # Set the default working directory

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./application/${{ matrix.project }}/package-lock.json

      - name: Install dependencies
        run: npm ci

      #- name: Run linters
      #  uses: wearerequired/lint-action@v2
      #  with:
      #    eslint: true
      #    prettier: true

      #- name: Build
      #  run: npm run build --if-present

      - name: Test
        run: npm test
        
      - name: Audit
        continue-on-error: true
        run: npm audit 
  
              
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
             
             
     
