name: pull requests testing

on:
  pull_request:

jobs:
  cypress-run:
      runs-on: ubuntu-22.04
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        # Install NPM dependencies, cache them correctly
        # and run all Cypress tests
        - name: Cypress run
          uses: cypress-io/github-action@v5
          with:
            build: npm run build
            start: npm start

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        project: [frontend, api]

    defaults:
      run:
        working-directory: ./application/${{ matrix.project }} # Set the default working directory

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./application/${{ matrix.project }}/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run linters
        run: npm run lint
        continue-on-error: true

      - name: Build
        run: npm run build --if-present

      - name: Test
        run: npm test
        
      - name: Audit
        continue-on-error: true
        run: npm audit
        
